FROM python:3.12-slim

WORKDIR /app

COPY src/task_handler.py .
COPY data/tasks_data.json ./data/

ENV INPUT_FILE=/app/data/processes.json

ENTRYPOINT ["python", "task_handler.py", "--algorithm", "rr", "--input", "/app/data/tasks_data.json"]
CMD ["--quantum", "2"]